# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=ppc64
TARGET_ABI_DIR=ppc
TARGET_WORDS_BIGENDIAN=yes
CONFIG_USER_ONLY=yes
CONFIG_LINUX_USER=yes
TARGET_XML_FILES= /home/sudarsun/devel/kernels/xen-hv/tools/ioemu-qemu-xen/gdb-xml/power64-core.xml /home/sudarsun/devel/kernels/xen-hv/tools/ioemu-qemu-xen/gdb-xml/power-fpu.xml /home/sudarsun/devel/kernels/xen-hv/tools/ioemu-qemu-xen/gdb-xml/power-altivec.xml /home/sudarsun/devel/kernels/xen-hv/tools/ioemu-qemu-xen/gdb-xml/power-spe.xml
CONFIG_SOFTFLOAT=yes
