# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=m68k
TARGET_WORDS_BIGENDIAN=yes
CONFIG_SOFTMMU=yes
TARGET_XML_FILES= /usr/src/xen-hv/tools/ioemu-qemu-xen/gdb-xml/cf-core.xml /usr/src/xen-hv/tools/ioemu-qemu-xen/gdb-xml/cf-fp.xml
CONFIG_SOFTFLOAT=yes
