# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=arm
CONFIG_SOFTMMU=yes
TARGET_XML_FILES= /usr/src/xen-hv/tools/ioemu-qemu-xen/gdb-xml/arm-core.xml /usr/src/xen-hv/tools/ioemu-qemu-xen/gdb-xml/arm-vfp.xml /usr/src/xen-hv/tools/ioemu-qemu-xen/gdb-xml/arm-vfp3.xml /usr/src/xen-hv/tools/ioemu-qemu-xen/gdb-xml/arm-neon.xml
CONFIG_SOFTFLOAT=yes
